apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL25lb25kYl9vd25lcjpwZ2lfaUk0UVJuNmxhd0plQGVwLXJhc3B5LWNha2UtYWJzeGxjbnItcG9vbGVyLmV1LXdlc3QtMi5hd3MubmVvbi50ZWNoL25lb25kYj9zc2xtb2RlPXJlcXVpcmU=
  BETTER_AUTH_SECRET: MjZXaUxvV2tTYnRta3dkcmhSUjNPdXRXZ0ZGbnhnc04=
  OPENAI_API_KEY: c2stb3ItdjEtNzQxZGQ3NDVkZmFlMDZiYjdhZjFjYWY1NjY1OGMwNjQ2ZTY2YzA3MTZiYjU0OWZhODY2Yjg3MWRlZGYxOTg4OQ==
  BETTER_AUTH_URL: aHR0cHM6Ly90b2RvLXdpdGgtY2hhdGJvdC52ZXJjZWwuc2pp