apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: todo-backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: todo-backend