apiVersion: v1
kind: Secret
metadata:
  name: todo-chatbot-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  auth_secret: {{ .Values.secrets.BETTER_AUTH_SECRET | b64enc | quote }}
  database_url: {{ .Values.secrets.DATABASE_URL | b64enc | quote }}
  openai_api_key: {{ .Values.secrets.OPENAI_API_KEY | b64enc | quote }}