apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secret-store
  namespace: todo-app
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
  - name: "default"
    value: "true"
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: app-secrets
  namespace: todo-app
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
  - name: "default"
    value: "true"