apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: todo-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: todo-frontend